# Generated by Django 5.2.4 on 2025-07-05 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
                ('action', models.CharField(blank=True, max_length=100, null=True)),
                ('repo_name', models.CharField(blank=True, max_length=255, null=True)),
                ('actor', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('commit_id', models.CharField(blank=True, max_length=40, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pull_request_number', models.IntegerField(blank=True, null=True)),
                ('pull_request_title', models.TextField(blank=True, null=True)),
                ('base_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('head_branch', models.CharField(blank=True, max_length=255, null=True)),
                ('review_state', models.CharField(blank=True, max_length=50, null=True)),
                ('payload', models.JSONField()),
            ],
            options={
                'db_table': 'github_events_collection',
                'ordering': ['-timestamp'],
            },
        ),
    ]
